version: 2
updates:
  - directory: /
    open-pull-requests-limit: 1
    package-ecosystem: github-actions
    rebase-strategy: auto
    schedule:
      interval: monthly
    groups:
      github-actions:
        patterns:
          - "*"
