[package]
name = "pkg-info-update"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.75", default-features = false, features = ["std"] }
clap = { version = "4.4.6", default-features = false, features = ["std", "color", "help", "usage", "error-context", "suggestions", "derive"] }
env_logger = { version = "0.10.0", default-features = false, features = ["auto-color", "color", "humantime"] }
log = { version = "0.4.20", default-features = false }
reqwest = { version = "0.11.20", default-features = false, features = ["default-tls", "stream", "gzip"] }
serde = { version = "1.0.188", default-features = false, features = ["std", "derive"] }
url = { version = "2.4.1", default-features = false, features = ["serde"] }
serde_json = { version = "1.0.107", default-features = false, features = ["std", "preserve_order"] }
thiserror = { version = "1.0.49", default-features = false }
futures = { version = "0.3.28", default-features = false, features = ["std"] }
itertools = "0.11.0"
tokio = { version = "1.32.0", default-features = false, features = ["rt", "rt-multi-thread"] }
sha2 = { version = "0.10.8", default-features = false, features = ["std"] }
regex = { version = "1.9.6", default-features = false, features = ["std", "perf"] }

[dev-dependencies]
rstest = { version = "0.18.2", default-features = false }
